name: 'Build and Push DevContainer'
description: 'Builds and pushes a devcontainer image with SemVer tags'
inputs:
  image_name:
    description: 'Name of the image (e.g., ubuntu-base)'
    required: true
  image_folder:
    description: 'Path to the folder (e.g., src/ubuntu-base)'
    required: true
  target_version:
    description: 'Version to tag (e.g., 0.4.5) - only used if is_target is true'
    required: true
  is_target:
    description: 'Whether this is the target image being tagged (true/false)'
    required: true
  registry:
    description: 'Container registry'
    default: 'ghcr.io'
  repo_owner:
    description: 'Repository Owner'
    required: true
  repo_name:
    description: 'Repository Name'
    required: true
  token:
    description: 'GitHub Token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.repo_owner }}
        password: ${{ inputs.token }}

    - name: Generate Tags
      id: tags
      shell: bash
      env:
        IS_TARGET: ${{ inputs.is_target }}
        VERSION: ${{ inputs.target_version }}
        REGISTRY: ${{ inputs.registry }}
        REPO_OWNER: ${{ inputs.repo_owner }}
        REPO_NAME: ${{ inputs.repo_name }}
        IMAGE_NAME: ${{ inputs.image_name }}
      run: |
        # Generate appropriate tags based on whether this is the target image or a dependency
        BASE_IMAGE="$REGISTRY/$REPO_OWNER/$REPO_NAME/$IMAGE_NAME"

        if [ "$IS_TARGET" = "true" ]; then
          # This is the target image - generate full semver tags
          echo "Generating semver tags for target image..."

          # Start with latest
          TAGS="$BASE_IMAGE:latest"

          # Parse version (already cleaned of 'v' prefix by workflow)
          if [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            MAJOR=$(echo "$VERSION" | cut -d. -f1)
            MINOR=$(echo "$VERSION" | cut -d. -f1,2)
            PATCH="$VERSION"

            # Add semver tags with full image name
            TAGS="$TAGS,$BASE_IMAGE:$MAJOR,$BASE_IMAGE:$MINOR,$BASE_IMAGE:$PATCH"
            echo "Generated semver tags: $TAGS"
          else
            echo "Warning: Version $VERSION doesn't match semver pattern X.Y.Z"
            echo "Using: latest,$VERSION"
            TAGS="$TAGS,$BASE_IMAGE:$VERSION"
          fi
        else
          # This is a dependency being rebuilt - only tag as latest
          echo "Building dependency image - tagging as latest only"
          TAGS="$BASE_IMAGE:latest"
        fi

        # Convert comma-separated to space-separated and create --tag arguments
        TAG_ARGS=""
        IFS=',' read -ra TAG_ARRAY <<< "$TAGS"
        for tag in "${TAG_ARRAY[@]}"; do
          TAG_ARGS="$TAG_ARGS --tag $tag"
        done

        # Convert --tag args to comma-separated list for devcontainers/ci
        TAGS=$(echo "$TAG_ARGS" | sed 's/--tag //g' | tr ' ' '\n' | grep -v '^$' | awk -F':' '{print $2}' | paste -sd ',' -)

        echo "tags=$TAG_ARGS" >> $GITHUB_OUTPUT
        echo "imagetags=$TAGS" >> $GITHUB_OUTPUT
        echo "cache_from=$BASE_IMAGE:latest" >> $GITHUB_OUTPUT

    - name: Build and Push
      uses: devcontainers/ci@v0.3.1900000417
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      with:
        imageName: ${{ inputs.registry }}/${{ inputs.repo_owner }}/${{ inputs.repo_name }}/${{ inputs.image_name }}
        subFolder: ${{ inputs.image_folder }}
        push: always
        imageTag: ${{ steps.tags.outputs.imagetags }}
        platform: linux/amd64,linux/arm64
        cacheFrom: ${{ inputs.registry }}/${{ inputs.repo_owner }}/${{ inputs.repo_name }}/${{ inputs.image_name }}:latest
